name: chem531
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - ipython
  - nb_conda
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - notebook
  - pandas
  - python==3.7
  - scipy
  - yaml
  - numpy
  - matplotlib
